FROM golang:1.22-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /controller ./cmd/controller

FROM alpine:3.20

WORKDIR /app
COPY --from=build /controller /app/controller
COPY --from=build /app/migrations /app/migrations

EXPOSE 8080

CMD ["/app/controller"]
