apiVersion: v1
kind: ConfigMap
metadata:
  name: network-controller-config
  labels:
    app.kubernetes.io/part-of: distributed-go-network-controller
data:
  SERVICE_PORT: "8080"
  WORKER_CONCURRENCY: "3"
  VITE_PROXY_TARGET: "http://controller:8080"
  POSTGRES_DB: network_controller
  POSTGRES_USER: postgres
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
