apiVersion: v1
kind: Secret
metadata:
  name: network-controller-secrets
  labels:
    app.kubernetes.io/part-of: distributed-go-network-controller
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/network_controller?sslmode=disable
